# railway.toml

[env]
RAILWAY_GIT_BRANCH = "main"  # Reemplaza con tu rama Git si es diferente

[services]
  [services.default]
    command = "node js/app.js"  # Ruta correcta a tu app.js
    internal_port = 3000  # Puerto interno donde corre tu aplicación

[build]
  builder = "nixpacks/build"
  port = 3000
